packages:
  - docs
  - packages/hydration/
  - packages/prerender/
  - packages/headings/
  - packages/mdx/
  - packages/excerpt/
  - packages/feed/
  - packages/icons/
  - packages/i18n/
  - packages/pages/
  - packages/prism/
  - packages/iles/
  - playground/the-vue-point/
